ParserSite/Models/parser/Part.cs
namespace ParserSite
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Entity;
    using System.Linq;

    public class Part
    {
        public int Id { get; set; }
        //public int OrderId { get; set; }
        [Required]
        public string PartNumber { get; set; }
        public string PartName { get; set; }
        
        public virtual Order Order { get; set; }
        public virtual ICollection<ParsedData> ParsedDatas { get; set; }
    }
}

ParserSite/Controllers/ParsedDatasController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ParserLibrary;

namespace ParserSite.Controllers
{
    public static class MyExtentions
    {
        public static List<ParsedData> ToParsedData(this Vmax44ParserConnectedLayer.ParsedDataCollection parsed)
        {
            List<ParsedData> result = new List<ParsedData>();
            foreach (var p in parsed)
            {
                ParsedData r = new ParsedData();
                r.Description = p.desc;
                r.Firmname = p.firmname;
                r.Original = p.orig;
                r.ParseDate = DateTime.Now;
                r.ParserType = p.parsertype;
                r.Price = p.price;
                r.SearchedArtikul = p.searchedArtikul;
                r.Statistic = p.statistic;
                r.Url = p.url;
                result.Add(r);
            }
            return result;
        }
    }


    public class ParseState
    {
        public int[] selectedParts;
        public int[] selectedParsers;
        public int OrderId;
        public int currentPart;
        public int currentParser;
        public Dictionary<int, List<ParsedData>> parsed;
        public Dictionary<int, string> SelectedStrings = new Dictionary<int, string>();
        public List<string> log = new List<string>();
        public List<string> parserslog = new List<string>();

        public ParseState()
        {
            parsed = new Dictionary<int, List<ParsedData>>();
            currentParser = 0;
            currentPart = 0;
        }
    }

    public class ParsedDatasController : Controller
    {
        private ParserContext db = new ParserContext();

        private void AddError(string s)
        {
            if (TempData["Errors"] == null)
            {
                TempData["Errors"] = new List<string>();
            }
            (TempData["Errors"] as List<string>).Add(s);
        }

        // POST: Form to select parsers and start parse
        [HttpPost]
        public ActionResult Parse(int[] selectedParts, int OrderId)
        {
            if (selectedParts == null)
            {
                AddError("Выберите элементы для парсинга");
                return RedirectToAction("Details", "Orders", new { Id = OrderId });
            }
            ViewBag.SelectedParts = selectedParts;
            ViewBag.OrderId = OrderId;
            ParsersManager pm = new ParsersManager();
            return View(pm.GetAvailableParsers());
        }

        // POST: Start parse process and return parsed data
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult StartParse(int[] selectedParts, int OrderId, int[] selectedParsers)
        {
            if (selectedParts == null)
            {
                AddError("Выберите элементы для парсинга");
                return RedirectToAction("Details", "Orders", new { Id = OrderId });
            }
            if (selectedParsers == null)
            {
                AddError("Выберите необходимые парсеры");
                return RedirectToAction("Parse", new { OrderId = OrderId });
            }
            ParseState st = new ParseState()
             {
                 selectedParsers = selectedParsers,
                 selectedParts = selectedParts,
                 OrderId = OrderId
             };
            Session.Add("state", st);
            return StartParse2(string.Empty);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult StartParse2(string selectedString)
        {
            ParseState st = (ParseState)Session["state"]; //достаем из сессии информацию о текущем состоянии парсинга
            if (st == null)
            {
                return HttpNotFound();
            }
            Order order = db.Orders.Find(st.OrderId);
            ParsersManager pm = new ParsersManager();
            var parsers = pm.GetParsersByArrayIds(st.selectedParsers); //получаем необходимые парсеры
            foreach (KeyValuePair<int, string> kvp in st.SelectedStrings)
            {
                parsers[kvp.Key].setSelectedString(kvp.Value); //сохраняем в парсеры ранее выбранных производителей
            }
            bool juststarted = true; //переменная для того, чтобы определить, что мы только что попали в функцию
            //и необходимо продолжить парсить тем парсером, на котором остановились ранее
            for (; st.currentPart < st.selectedParts.Count(); st.currentPart++)
            {
                var dbpart = db.Parts.Find(st.selectedParts[st.currentPart]);
                if (juststarted)
                {
                    juststarted = false;
                }
                else
                {
                    st.currentParser = 0;
                }
                for (; st.currentParser < st.selectedParsers.Count(); st.currentParser++)
                {
                    if (selectedString != string.Empty)   //если выбрана новая строка
                    {
                        st.SelectedStrings.Add(st.currentParser, selectedString);  //сохраняем ее в объект статуса
                        parsers[st.currentParser].setSelectedString(selectedString); //а также в соответствующий парсер
                        selectedString = string.Empty;
                    }
                    var parsertype = parsers[st.currentParser].GetParserType();
                    var PartNumber = from part in order.Parts
                                     where part.Id == st.selectedParts[st.currentPart]
                                     select part.PartNumber;
                    st.log.Add(string.Format(" парсим деталь {0} на сайте {1}...", PartNumber.First(), parsertype));
                    var r = parsers[st.currentParser].detailParse(PartNumber.First()).ToParsedData();
                    switch (parsers[st.currentParser].getError())
                    {
                        case 1:
                            st.log.Add("!требуется выбор производителя");
                            DisposeParsers(st, parsers);
                            ViewBag.st = st;
                            Session["state"] = st;
                            return PartialView("_SelectManufacturer", parsers[st.currentParser].getStringsToSelect());
                        case 0:
                            st.log.Add(string.Format("Ok. напарсено {0} результатов", r.Count));
                            if (st.parsed.ContainsKey(st.currentPart))
                            {
                                st.parsed[st.currentPart].AddRange(r);
                            }
                            else
                            {
                                st.parsed[st.currentPart] = r;
                            }
                            break;
                        case 2:
                            break;
                        default:
                            break;
                    }
                }
            }
            DisposeParsers(st, parsers);
            ViewBag.st = st;
            return PartialView("StartParse");
        }

        private static void DisposeParsers(ParseState st, List<Vmax44Parser.library.IParser> parsers)
        {
            foreach (var parser in parsers)
            {
                st.parserslog.AddRange(parser.GetLog());
                parser.Dispose();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveParse()
        {
            DateTime saveDate = DateTime.Now;
            ParseState st = (ParseState)Session["state"];
            if (st == null)
            {
                return HttpNotFound();
            }

            Order order = db.Orders.Find(st.OrderId);
            foreach (KeyValuePair<int, List<ParsedData>> p in st.parsed)
            {
                Part part = db.Parts.Find(st.selectedParts[p.Key]);
                foreach (ParsedData entry in p.Value)
                {
                    entry.Order = order;
                    entry.Part = part;
                    entry.ParseDate = saveDate;
                    order.ParsedDatas.Add(entry);
                }
            }
            db.SaveChanges();
            Session.Remove("state");
            return RedirectToAction("Details", "Orders", new { id = st.OrderId });
        }

        // GET: ParsedDatas
        public ActionResult Index(int OrderId)
        {
            ViewBag.OrderId = OrderId;
            var order = db.Orders.Find(OrderId);
            if (order == null)
            {
                return HttpNotFound();
            }
            return PartialView("_ParsedDataPartial", order.ParsedDatas.ToList());
        }

        // GET: ParsedDatas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ParsedData parsedData = db.ParsedDatas.Find(id);
            if (parsedData == null)
            {
                return HttpNotFound();
            }
            return View(parsedData);
        }

        // GET: ParsedDatas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ParsedDatas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ParseDate,ParserType,Original,Firmname,Description,Statistic,Price,SearchedArtikul,Url")] ParsedData parsedData)
        {
            if (ModelState.IsValid)
            {
                db.ParsedDatas.Add(parsedData);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

ParserSite/Controllers/PartsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ParserSite;
using System.Threading;

namespace ParserSite.Controllers
{
    public class PartsController : Controller
    {
        private ParserContext db = new ParserContext();

        // GET: Parts
        public ActionResult Index(int? OrderId)
        {
            if (OrderId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order o = db.Orders.Find(OrderId);
            if (o == null)
            {
                return HttpNotFound();
            }
            ViewBag.OrderId = OrderId;
            return View(o);
        }

        // GET: Parts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Part part = db.Parts.Find(id);
            if (part == null)
            {
                return HttpNotFound();
            }
            return View(part);
        }

        // GET: Parts/Create
        public ActionResult Create(int OrderId)
        {
            ViewBag.OrderId = OrderId;
            return PartialView();
        }

        // POST: Parts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,PartNumber,PartName")] Part part,int OrderId)
        {
            ViewBag.OrderId = OrderId;
            if (ModelState.IsValid)
            {
                var o = db.Orders.Find(OrderId);
                if (o == null)
                {
                    return HttpNotFound();
                }
                o.Parts.Add(part);
                db.SaveChanges();
                //Thread.Sleep(5000);
                return PartialView(new Part());
                //return RedirectToAction("Index", "Parts", new { OrderId = OrderId });
            }

            return PartialView(part);
        }

        // GET: Parts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Part part = db.Parts.Find(id);
            if (part == null)
            {
                return HttpNotFound();
            }
            return View(part);
        }

        // POST: Parts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,PartNumber,PartName")] Part part)
        {
            if (ModelState.IsValid)
            {
                db.Entry(part).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index","Orders",null);
            }
            return View(part);
        }

        // GET: Parts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Part part = db.Parts.Find(id);
            if (part == null)
            {
                return HttpNotFound();
            }
            return View(part);
        }

        // POST: Parts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public void Delete(int[] selectedparts, int OrderId)
        {
            
            var o = db.Orders.Find(OrderId);
            if (o != null && selectedparts != null)
            {
                var s = from p in o.Parts
                        where selectedparts.Contains(p.Id)
                        where p.ParsedDatas.Count==0
                        select p;
                
                foreach (var p in s.ToList())
                {
                    db.Parts.Remove(p);
                    //o.Parts.Remove(p);
                }
                
                db.SaveChanges();
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ParserSite/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ParserSite;

namespace ParserSite.Controllers
{
    public class ReportsController : Controller
    {
        private ParserContext db = new ParserContext();

        // POST: Reports/Test
        [HttpPost]
        public ActionResult Test(int[] selectedparts,int OrderId)
        {
            if (selectedparts == null)
            {
                return HttpNotFound();
            }
            var order = db.Orders.Find(OrderId);
            List<ParsedData> datas = new List<ParsedData>();
            foreach (var partid in selectedparts)
            {
                var part = order.Parts.Where(p => p.Id == partid)
                    .First();
                datas.AddRange(part.ParsedDatas);
            }
            return View(datas);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ParserSite/Views/Parts/Create.cshtml
@model ParserSite.Part

@using (Html.BeginForm("Create", "Parts", new { OrderId = ViewBag.OrderId },FormMethod.Post,
    new
    {
        @class="well form-inline",
        id = "parts_create_form",
        onsubmit = "AjaxFormRequest_func('parts_create_form','" +
        @Url.Action("Create", "Parts", new { OrderId = ViewBag.OrderId }) +
        "', part_created_ok, part_created_error);return false;"
    }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                @Html.EditorFor(model => model.PartNumber, new { htmlAttributes = new { @class = "input-small",
                                        placeholder="Номер"} })
                @Html.ValidationMessageFor(model => model.PartNumber, "", new { @class = "text-danger" })

                @Html.EditorFor(model => model.PartName, new { htmlAttributes = new { @class = "input-small", 
                                        placeholder="Наименование"} })
                @Html.ValidationMessageFor(model => model.PartName, "", new { @class = "text-danger" })
                <input type="submit" value="Add" class="btn btn-default" />
                <a href="#" class="btn btn-default" onclick="Parts_Delete_Click(); return false;">Delete</a>
                <a href="#" class="btn btn-default" onclick="Parts_Parse_Click('@Url.Action("Parse", "ParsedDatas",
                new { OrderId = ViewBag.OrderId })'); return false;">Parse!</a>
                <a href="#" class="btn btn-default" onclick="Parts_Parse_Click('@Url.Action("Test", "Reports",
                    new { OrderId = ViewBag.OrderId })'); return false;">Report</a>

}

ParserSite/Views/Parts/Delete.cshtml
@model ParserSite.Part

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Part</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PartNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PartNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PartName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PartName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ParserSite/Views/Parts/Details.cshtml
@model ParserSite.Part

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Part</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PartNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PartNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PartName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PartName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ParserSite/Views/Parts/Edit.cshtml
@model ParserSite.Part

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Part</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.PartNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PartNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PartNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PartName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PartName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PartName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ParserSite/Views/Parts/Index.cshtml
@model Order
@{Layout = null;}
@Html.Partial("_PartsPartial",Model)